import "./globals.css";
import { Inter } from "next/font/google";
import NavBarComponet from "@/components/navBarComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gabriel NA",
  description: "Generated by create next app",
  icons: {
    icon: "/img/defLogoNbg.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <NavBarComponet />
        {children}
      </body>
    </html>
  );
}
